// Verdict question bank. Add, remove, or edit freely.
// Each question's ID is derived from its text, so editing a question's wording
// starts fresh history for it; reordering or adding questions is always safe.
const QUESTION_BANK = {
  "Everyday": [
    "Would you rather cook at home tonight than order out?",
    "Is it okay to leave dishes in the sink overnight?",
    "Should you make your bed every morning?",
    "Would you take a 20-minute nap right now if you could?",
    "Is it worth waking up an hour earlier to have quiet time?",
    "Would you skip your phone for the first hour of the day?",
    "Should you reply to every text the same day?",
    "Would you rather run errands on Saturday morning than Sunday?",
    "Is it fine to wear the same outfit two days in a row?",
    "Would you pay extra for same-day delivery on something you want?",
    "Should you declutter one drawer today?",
    "Would you rather have a clean house than an extra free hour?",
    "Is it okay to cancel plans because you're simply tired?",
    "Would you go to a movie alone?",
    "Should you answer a phone call from an unknown number?",
    "Would you rather shower in the morning than at night?",
    "Is it worth ironing clothes?",
    "Would you give up your favorite TV show for a month to read more?",
    "Should you keep your email inbox at zero?",
    "Would you rather walk 30 minutes than drive 10?",
    "Is it rude to wear headphones while someone is talking nearby?",
    "Would you let a friend borrow your car?",
    "Should you buy groceries with a strict list?",
    "Would you rather be ten minutes early than exactly on time?",
    "Is it okay to leave a voicemail instead of texting?"
  ],
  "Food & Drink": [
    "Would you eat the same breakfast every day for a year?",
    "Does pineapple belong on pizza?",
    "Would you try insects if they were served at a nice restaurant?",
    "Should you finish your plate even when you're full?",
    "Would you give up coffee for a month?",
    "Is a hot dog a sandwich?",
    "Would you rather have dessert than an appetizer?",
    "Would you eat at a restaurant with no menu, where the chef decides?",
    "Should you send food back if it's not quite what you ordered?",
    "Would you go vegetarian for a month?",
    "Is cereal a soup?",
    "Would you pay $200 for a once-in-a-lifetime tasting menu?",
    "Would you rather eat spicy food than bland food?",
    "Should you tip on takeout orders?",
    "Would you learn to bake bread from scratch?",
    "Would you eat food that fell on the floor for three seconds?",
    "Is breakfast the most important meal of the day?",
    "Would you give up sugar for 30 days?",
    "Would you try a cuisine you've never heard of today?",
    "Should you eat dinner at the table instead of in front of a screen?",
    "Would you rather have unlimited sushi than unlimited tacos?",
    "Is it okay to bring your own snacks into a movie theater?",
    "Would you grow your own vegetables?",
    "Should leftovers be eaten for breakfast?",
    "Would you eat a meal entirely chosen by a stranger?"
  ],
  "Travel & Adventure": [
    "Would you travel somewhere without booking a place to stay?",
    "Would you go skydiving?",
    "Would you rather visit a big city than go camping?",
    "Would you take a one-way trip to Mars?",
    "Should you travel alone at least once in your life?",
    "Would you live abroad for a year?",
    "Would you take a 30-hour train ride instead of a 3-hour flight?",
    "Would you go on a cruise?",
    "Would you rather visit 20 countries briefly than live in one deeply?",
    "Would you swim with sharks in a cage?",
    "Should you plan every day of a vacation in advance?",
    "Would you spend a night in a supposedly haunted hotel?",
    "Would you hike a multi-week trail like the Pacific Crest Trail?",
    "Would you go somewhere you don't speak the language at all?",
    "Would you take a spontaneous trip leaving tomorrow?",
    "Would you rather travel by road trip than by plane?",
    "Would you go to Antarctica if it were free?",
    "Should you put your phone away for an entire vacation?",
    "Would you stay in a hostel dorm?",
    "Would you climb a mountain over 14,000 feet?",
    "Would you go back to the same vacation spot every year?",
    "Would you bungee jump?",
    "Would you spend a week completely off-grid?",
    "Would you rather see the Northern Lights than the pyramids?",
    "Would you sail across an ocean on a small boat?"
  ],
  "Money": [
    "Would you take $1 million now instead of $50,000 a year for life?",
    "Should you have six months of expenses in savings before investing?",
    "Would you lend a close friend $1,000?",
    "Is it worth paying more for a brand you trust?",
    "Would you buy a used car over a new one?",
    "Should you rent rather than buy a home?",
    "Would you take a 20% pay cut for a four-day work week?",
    "Would you rather spend money on experiences than things?",
    "Should you tell friends how much you earn?",
    "Would you buy lottery tickets regularly?",
    "Would you pay off all debt before saving for retirement?",
    "Would you spend $500 on a really good mattress?",
    "Should couples combine all their finances?",
    "Would you invest in a friend's startup?",
    "Would you cancel a subscription you used only once last month?",
    "Is it okay to splurge on something purely to cheer yourself up?",
    "Would you live with roommates to save money?",
    "Would you buy something expensive and wait 30 days before deciding to keep it?",
    "Should you negotiate the price at a car dealership?",
    "Would you rather be rich and busy than modestly off and free?",
    "Would you give 10% of your income to charity?",
    "Should children get an allowance?",
    "Would you use a credit card for every purchase to earn points?",
    "Would you retire early on a smaller budget?",
    "Would you sell something sentimental for a lot of money?"
  ],
  "Career & Work": [
    "Would you take a dream job that paid 30% less?",
    "Should you answer work emails on weekends?",
    "Would you start your own business?",
    "Would you rather work remotely full-time than in an office?",
    "Should you ask for a raise this year?",
    "Would you go back to school for a new career?",
    "Would you work for a company whose product you dislike?",
    "Is it okay to have a side hustle without telling your employer?",
    "Would you rather be a great manager than a great individual contributor?",
    "Would you take a job that requires moving across the country?",
    "Should you stay at one company for over ten years?",
    "Would you accept a promotion that means much longer hours?",
    "Is it acceptable to leave a job after six months?",
    "Would you work a job you're passionate about for minimum wage?",
    "Would you speak up in a meeting if you disagreed with your boss?",
    "Should you be friends with your coworkers outside of work?",
    "Would you take a sabbatical for a year, unpaid?",
    "Would you rather have a famous job or a well-paid unknown one?",
    "Should you work while you're sick if you're remote?",
    "Would you hire a friend?",
    "Would you volunteer to lead a project nobody wants?",
    "Is it important to love your job?",
    "Would you change careers at 50?",
    "Should you put a hobby on your resume?",
    "Would you work a four-day week of ten-hour days?"
  ],
  "Relationships": [
    "Would you tell a friend their partner is cheating?",
    "Should you stay friends with an ex?",
    "Would you rather have a few close friends than many acquaintances?",
    "Is it okay to read your partner's texts?",
    "Would you move for a partner's career?",
    "Should you say \"I love you\" first?",
    "Would you go on a blind date set up by a friend?",
    "Would you forgive a friend who lied to you about something serious?",
    "Should couples take separate vacations sometimes?",
    "Would you call a friend you haven't talked to in years today?",
    "Is it okay to end a friendship by slowly drifting away?",
    "Would you live next door to your parents?",
    "Should you share passwords with your partner?",
    "Would you tell someone they have something in their teeth?",
    "Would you date someone with very different political views?",
    "Should you tell a friend you didn't like their gift?",
    "Would you lend money to family?",
    "Would you attend a wedding you weren't excited about to keep the peace?",
    "Should you apologize first even if you think you're right?",
    "Would you rather be the one who loves more in a relationship?",
    "Would you set up two friends you think would be good together?",
    "Is it okay to have a best friend of the gender you're attracted to while in a relationship?",
    "Would you confront a friend about a hurtful joke?",
    "Should you meet online friends in person?",
    "Would you tell your partner about every past relationship?"
  ],
  "Ethics": [
    "Would you return a wallet with $500 in it and no one watching?",
    "Is it okay to lie to protect someone's feelings?",
    "Would you report a coworker you saw stealing small amounts?",
    "Should you tell a cashier if they give you too much change?",
    "Would you divert a runaway trolley to kill one person instead of five?",
    "Is it okay to break a law you think is unjust?",
    "Would you take credit for an idea if the real author never found out?",
    "Should you tell the truth even if it costs you your job?",
    "Would you eat meat if you had to slaughter the animal yourself?",
    "Is it wrong to pirate something that's no longer sold anywhere?",
    "Would you steal medicine to save a loved one's life?",
    "Should rich people be required to give more to charity?",
    "Would you keep a promise to someone who has died, even if it's inconvenient?",
    "Is it okay to use a friend's streaming account without paying?",
    "Would you lie on a résumé if you knew you could do the job?",
    "Should you tell a stranger their child is misbehaving?",
    "Would you sacrifice your own life to save five strangers?",
    "Is it okay to call in sick for a mental health day?",
    "Would you report a friend for drunk driving?",
    "Is it ever okay to break a promise?",
    "Would you give money to someone asking on the street?",
    "Should you tell a friend a hard truth they didn't ask for?",
    "Would you accept an unfair advantage in a competition if no one would know?",
    "Is it okay to eavesdrop on an interesting conversation in public?",
    "Would you keep extra items you weren't charged for in an online order?"
  ],
  "Hypotheticals": [
    "Would you want to know the date of your death?",
    "Would you live forever if you could?",
    "Would you erase a painful memory if you could?",
    "Would you rather be able to fly than be invisible?",
    "Would you swap lives with a random person for a year?",
    "Would you want to read minds, even if you couldn't turn it off?",
    "Would you go back in time and change one decision?",
    "Would you accept $10 million to never use the internet again?",
    "Would you want to meet a future version of yourself?",
    "Would you rather be famous after death than during life?",
    "Would you upload your mind to a computer to live on?",
    "Would you give up all music to be able to speak every language?",
    "Would you clone yourself if you could?",
    "Would you rather know everything about the past than the future?",
    "Would you live in a simulation if it were perfect?",
    "Would you take a pill that made you never need sleep?",
    "Would you restart life at age 10 with your current memories?",
    "Would you push a button that gives you $1 million but makes a random stranger lose $1,000?",
    "Would you live in a world with no lying for anyone?",
    "Would you want to be the smartest person on Earth?",
    "Would you trade ten years of life for perfect health for the rest of it?",
    "Would you rather talk to animals than to the dead?",
    "Would you be the first person to try a teleporter?",
    "Would you spend a year alone in a cabin for $1 million?",
    "Would you want your whole life recorded and searchable?"
  ],
  "Technology": [
    "Would you ride in a fully self-driving car today?",
    "Should kids under 13 have smartphones?",
    "Would you get a brain implant to boost your memory?",
    "Would you delete all your social media accounts?",
    "Would you trust an AI to make medical decisions for you?",
    "Should you use a password manager?",
    "Would you give up your smartphone for a basic flip phone?",
    "Would you have a robot do all your household chores?",
    "Is it okay to use AI to write a heartfelt message to a friend?",
    "Would you wear smart glasses that record everything you see?",
    "Should screen time be limited for adults?",
    "Would you let your home be fully voice-controlled?",
    "Would you buy the newest phone the day it comes out?",
    "Should you read terms and conditions before agreeing?",
    "Would you date someone you met only in a virtual world?",
    "Would you hand over your location data for a 20% discount?",
    "Is technology making people lonelier?",
    "Would you go a full week with no screens at all?",
    "Would you let an AI choose your next vacation?",
    "Should you keep a physical copy of your important photos?",
    "Would you use a dating app that matched you by DNA?",
    "Would you rather have a faster computer than a bigger screen?",
    "Should you turn off all non-essential notifications?",
    "Would you want a personal AI that knows everything about you?",
    "Would you pay for an ad-free internet?"
  ],
  "Health & Lifestyle": [
    "Would you wake up at 5 a.m. every day for a month?",
    "Should you exercise even on days you feel unmotivated?",
    "Would you try a cold plunge?",
    "Would you give up alcohol for a year?",
    "Would you track every calorie for a week just to learn?",
    "Should you take a full rest day every week?",
    "Would you meditate for ten minutes every day for a month?",
    "Would you run a marathon?",
    "Would you rather sleep an extra hour than work out?",
    "Should you go to the doctor for a minor issue you're unsure about?",
    "Would you try a silent retreat for a weekend?",
    "Would you join a team sport as an adult?",
    "Would you try therapy even if nothing feels wrong?",
    "Should you keep a journal?",
    "Would you walk 10,000 steps every day for a month?",
    "Would you go to bed at the same time every night, weekends included?",
    "Would you hire a personal trainer?",
    "Should you take a break from caffeine once a year?",
    "Would you learn to swim if you couldn't already?",
    "Would you rather exercise in the morning than the evening?",
    "Would you spend a weekend doing nothing at all?",
    "Should you say no to an invitation to protect your rest?",
    "Would you take up yoga?",
    "Would you get regular massages if money were no object?",
    "Would you do a digital detox one day a week?"
  ],
  "Society": [
    "Should voting be mandatory?",
    "Should the voting age be lowered to 16?",
    "Is a four-day work week good for society?",
    "Should public transit be free?",
    "Should homework be banned in elementary school?",
    "Should tipping be replaced with higher wages?",
    "Should college be free?",
    "Should everyone do a year of community service?",
    "Is it a good idea to ban phones in schools?",
    "Should daylight saving time be abolished?",
    "Should zoos exist?",
    "Should cities ban cars from their downtown areas?",
    "Should there be a universal basic income?",
    "Is space exploration worth the cost?",
    "Should single-use plastics be banned?",
    "Should people be paid for doing housework?",
    "Should cursive still be taught in schools?",
    "Should there be term limits for every elected office?",
    "Is social media good for democracy?",
    "Should restaurants be required to post calorie counts?",
    "Should we bring back extinct species if we could?",
    "Should homeowners be allowed to replace lawns with gardens anywhere?",
    "Should pets be allowed in offices?",
    "Is it better to have a smaller, slower-growing economy that's more sustainable?",
    "Should libraries be open 24 hours?"
  ],
  "Self & Values": [
    "Do you care what strangers think of you?",
    "Would you rather be respected than liked?",
    "Is it better to be safe than sorry?",
    "Would you rather be right than happy?",
    "Do you believe people can fundamentally change?",
    "Would you rather have a predictable life than an exciting one?",
    "Is it better to regret something you did than something you didn't do?",
    "Would you rather be a big fish in a small pond?",
    "Do you trust your gut more than data?",
    "Would you rather lead than follow?",
    "Is ambition more important than contentment?",
    "Would you choose wisdom over intelligence?",
    "Do you think luck matters more than effort?",
    "Would you rather give advice than receive it?",
    "Is it important to leave a legacy?",
    "Would you rather be remembered for kindness than achievement?",
    "Do you think it's okay to quit something you've committed to?",
    "Would you choose freedom over security?",
    "Is it better to forgive than to forget?",
    "Would you rather be underestimated than overestimated?",
    "Do you think you're the same person you were ten years ago?",
    "Would you rather know a hard truth than believe a comforting lie?",
    "Is it okay to want to be famous?",
    "Would you rather have a life full of small joys or a few huge ones?",
    "Do you make decisions faster than most people you know?"
  ]
};
